global:
  resolve_timeout: 2m
templates:     ##消息模板
  - '/etc/alertmanager/template/wechat.tmpl'

route:
  group_by: ['alertname_wechat']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'SunWenJu' # 优先使用wechat发送
receivers:
- name: 'SunWenJu'
  wechat_configs:
  - corp_id: 'ww578937f135427' #企业ID
    to_party: '1'  # 通知组ID
    agent_id: '1004'    
    api_secret: '5n4S-1j4Q2AR0LGLwghYtp3bGD2bkNr_SzQU' # 生成的secret
    send_resolved: true
