# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 172.17.0.6:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "rules/*.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'gz'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    #static_configs:
    #- targets: ['172.17.0.6:9090']
    file_sd_configs:
      - files: ['/etc/prometheus/prometheus.yml']
        refresh_interval: 5s

  - job_name: 'node'
    file_sd_configs:
      - files: ['/etc/prometheus/sd_config/*.yml']
        refresh_interval: 5s
  - job_name: 'docker'
    static_configs:
    - targets: ['172.17.0.6:8099']
   
  - job_name: 'mysql'
    static_configs:
    - targets: ['172.17.0.6:9104']
  
  - job_name: 'tomcat'
    static_configs:
    - targets: ['172.17.0.6:8989']

  - job_name: 'zookeeper'
    static_configs:
    - targets: ['172.17.0.6:2182']
